/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmtv0.UI;

import jmtv0.pkg0.Utility.HibernateUtil;
import Hibernate.Entity.CLASS;
import Hibernate.Entity.FEEBREAKUP;
import Hibernate.Entity.FEEDETAILS;
import Hibernate.Entity.STUDENT;
import Hibernate.Entity.STUDENTLEDGER;
import com.sun.org.apache.bcel.internal.generic.LCONST;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.List;
import javax.swing.ComboBoxModel;
import jmtv0.pkg0.Utility.Utility;
import org.hibernate.Session;

/**
 *
 * @author Lokesh
 */
public class ClassesList extends javax.swing.JPanel {

    private static final int SplitDividerDefault = 500;
    private static final int SplitDividerEnlarged = 400;
    private Vector searchData = null;
    private final DefaultTableModel dtmClassTable;
    private JFrame jf = null;
    private CLASS mClass;
    private DefaultTableModel dtmFeeBRUP;
    private DefaultTableModel dtmFee;
    Calendar start;
    Calendar end;

    /**
     * Creates new form SalesQuote
     */
    public ClassesList() {
        initComponents();
        dtmClassTable = (DefaultTableModel) classTable.getModel();
        dtmFee = (DefaultTableModel) feeTable.getModel();
        dtmFeeBRUP = (DefaultTableModel) feeBRUPTable.getModel();
        jSplitPane1.setDividerLocation(SplitDividerEnlarged);
        jf = new JFrame();
        jf.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        start = Calendar.getInstance();
        start.set(Calendar.HOUR, 0);
        start.set(Calendar.MINUTE, 0);
        start.set(Calendar.SECOND, 0);
        start.set(Calendar.MILLISECOND, 0);
        end = Calendar.getInstance();
        end.setTime(start.getTime());

        InitGui();
        serachButtonAction();
        fromYearTF.setText(start.get(Calendar.YEAR) + "");
        clearFeeAndFeeBRUPTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        ckBoxEdit = new javax.swing.JCheckBox();
        cancleButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfClassName = new javax.swing.JTextField();
        tfPanltyRate = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        comBoxPenaltyCycle = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        feeTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        feeBRUPTable = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        dayOfMonth = new javax.swing.JComboBox();
        fromYearTF = new javax.swing.JTextField();
        monthCB = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        durationTF = new javax.swing.JTextField();
        StudentList = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        monthStudenList = new javax.swing.JComboBox<String>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableStudentList = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Search1 = new javax.swing.JLabel();
        Search2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Search3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Search4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        Search5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Search6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        newButton.setText("New");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newButton);

        saveButton.setText("Save");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        ckBoxEdit.setText("EDIT");
        ckBoxEdit.setFocusable(false);
        ckBoxEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ckBoxEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ckBoxEdit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckBoxEditItemStateChanged(evt);
            }
        });
        jToolBar1.add(ckBoxEdit);

        cancleButton.setText("Cancle");
        cancleButton.setFocusable(false);
        cancleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cancleButton);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setVerifyInputWhenFocusTarget(false);

        jLabel25.setText("From Year ");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel30.setText("Penalty Cycle");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tfClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClassNameActionPerformed(evt);
            }
        });
        tfClassName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfClassNameKeyTyped(evt);
            }
        });

        tfPanltyRate.setEditable(false);
        tfPanltyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPanltyRateActionPerformed(evt);
            }
        });
        tfPanltyRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPanltyRateKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPanltyRateKeyReleased(evt);
            }
        });

        jLabel28.setText("Late Fee Penalty % ");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel52.setText("Class Name");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        comBoxPenaltyCycle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monthly" }));
        comBoxPenaltyCycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxPenaltyCycleActionPerformed(evt);
            }
        });

        jLabel1.setText("Fee");

        feeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feeTable.setColumnSelectionAllowed(true);
        feeTable.setOpaque(false);
        feeTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                feeTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(feeTable);
        feeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (feeTable.getColumnModel().getColumnCount() > 0) {
            feeTable.getColumnModel().getColumn(0).setResizable(false);
            feeTable.getColumnModel().getColumn(1).setResizable(false);
        }

        feeBRUPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Month", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feeBRUPTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                feeBRUPTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(feeBRUPTable);
        if (feeBRUPTable.getColumnModel().getColumnCount() > 0) {
            feeBRUPTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel32.setText("Due Day");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        dayOfMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        fromYearTF.setEditable(false);
        fromYearTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromYearTFFocusLost(evt);
            }
        });
        fromYearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromYearTFActionPerformed(evt);
            }
        });
        fromYearTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fromYearTFKeyTyped(evt);
            }
        });

        monthCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JUL", "AUG", "SEP", "OCT", "NOV", "DEC", "JAN", "FEB", "MAR", "APR", "MAY", "JUN" }));

        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Duration In Months");

        durationTF.setEditable(false);
        durationTF.setColumns(4);
        durationTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durationTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durationTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fromYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPanltyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comBoxPenaltyCycle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dayOfMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel28)
                    .addComponent(tfPanltyRate)
                    .addComponent(jLabel30)
                    .addComponent(comBoxPenaltyCycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayOfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel32)
                    .addComponent(fromYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(482, 482, 482))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Class Info", jPanel3);

        StudentList.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Month");

        monthStudenList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JUL", "AUG", "SEP", "OCT", "NOV", "DEC", "JAN", "FEB", "MAR", "APR", "MAY", "JUN" }));
        monthStudenList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthStudenListItemStateChanged(evt);
            }
        });

        tableStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableStudentList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthStudenList, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(monthStudenList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        StudentList.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("StudentList", StudentList);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel6FocusGained(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        Search1.setText("A/C Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search1, gridBagConstraints);

        Search2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        Search2.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel6.add(Search2, gridBagConstraints);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField1, gridBagConstraints);

        Search3.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search3, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField2, gridBagConstraints);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField3, gridBagConstraints);

        Search4.setText("Village");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search4, gridBagConstraints);

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel6.add(jButton6, gridBagConstraints);

        classTable.setAutoCreateRowSorter(true);
        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Year", "Penalty Cycle", "Penalty %"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        classTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        classTable.getTableHeader().setReorderingAllowed(false);
        classTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(classTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField4, gridBagConstraints);

        Search5.setText("Phone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search5, gridBagConstraints);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField5, gridBagConstraints);

        Search6.setText("Ocu./LastName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel6.add(Search6, gridBagConstraints);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel5);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        serachButtonAction();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        checkOfSave();
        serachButtonAction();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void classTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classTableMouseClicked
        if (!checkOfSave()) {
            Vector colsFeeBRUP = new Vector();
            colsFeeBRUP.addElement("Month");
            colsFeeBRUP.add("Tution Fee");
            colsFeeBRUP.add("Library Fee");
            colsFeeBRUP.add("Stationary Fee");
            colsFeeBRUP.add("Dress Fee");
            colsFeeBRUP.add("Misc. Fee");
            colsFeeBRUP.add("Total Fee");
            ckBoxEdit.setSelected(false);
            int ids = classTable.getSelectedRow();
            Object o = dtmClassTable.getValueAt(ids, 0);
            if (dtmClassTable.getValueAt(ids, 0) != null) {
                Session ses = HibernateUtil.getSessionFactory().openSession();
                try {
                    mClass = Utility.getClassWithID((int) dtmClassTable.getValueAt(ids, 0), ses);
                    updateClassForm();
                    Vector rowsFeeBRUP = new Vector();
                    List l = Utility.getFeeBrupListWithFeeDetailsID(mClass.getFeeDetails().getIdFeeDetails(), ses);
                    for (Object fee : l) {
                        Vector row = new Vector();
                        FEEBREAKUP lFeeBRUP = (FEEBREAKUP) fee;
                        Calendar c = Calendar.getInstance();
                        c.setTime(lFeeBRUP.getMonth());
                        String month = Utility.getMonthStrFromNum(c.get(Calendar.MONTH)) + "~" + c.get(Calendar.YEAR);
                        row.add(month);
                        if (lFeeBRUP != null) {
                            row.add(lFeeBRUP.getTutionFee());
                            row.add(lFeeBRUP.getLibraryFee());
                            row.add(lFeeBRUP.getStationaryFee());
                            row.add(lFeeBRUP.getDressFee());
                            row.add(lFeeBRUP.getMiscFee());
                            row.add(lFeeBRUP.getTotalFee());
                        }
                        rowsFeeBRUP.add(row);
                    }
                    DefaultTableModel dtmFeeBRUP = (DefaultTableModel) feeBRUPTable.getModel();
                    dtmFeeBRUP.setDataVector(rowsFeeBRUP, colsFeeBRUP);
                    newButton.setEnabled(true);
                } catch (Exception e) {
                } finally {
                    ses.close();
                }
                UpdateStudentList();
            }
        }
    }//GEN-LAST:event_classTableMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        SaveButtonAction();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        newButton.setEnabled(false);
        tfClassName.setText("");
        Calendar lc = Calendar.getInstance();
        lc.set(Calendar.HOUR, 0);
        lc.set(Calendar.MINUTE, 0);
        lc.set(Calendar.SECOND, 0);
        lc.set(Calendar.MILLISECOND, 0);
        start = lc;
        ckBoxEdit.setSelected(false);
        ckBoxEdit.setEnabled(false);
        tfClassName.setEditable(true);
        fromYearTF.setEditable(true);
        durationTF.setEditable(true);
        tfPanltyRate.setEditable(true);
        feeTable.setEnabled(true);
        feeBRUPTable.setEnabled(true);
        cancleButton.setEnabled(true);
        saveButton.setEnabled(true);
        Calendar ssr = Calendar.getInstance();
        start.set(Calendar.DATE, 1);
        start.set(Calendar.MONTH, 6);
    }//GEN-LAST:event_newButtonActionPerformed

    private void ckBoxEditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckBoxEditItemStateChanged
        if (tfClassName.getText().length() > 0) {
            if (ckBoxEdit.isSelected()) {
                newButton.setEnabled(false);
                cancleButton.setEnabled(true);
                saveButton.setEnabled(true);
                ckBoxEdit.setEnabled(false);
                tfClassName.setEditable(true);
                feeTable.setEnabled(true);
                feeBRUPTable.setEnabled(true);
                tfPanltyRate.setEditable(true);
                fromYearTF.setEditable(true);
                durationTF.setEditable(true);
            }
        } else {
            ckBoxEdit.setSelected(false);
        }
    }//GEN-LAST:event_ckBoxEditItemStateChanged

    private void jPanel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6FocusGained

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void feeBRUPTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeBRUPTableKeyReleased
        Vector fullVec = dtmFeeBRUP.getDataVector();
        Vector colSum = new Vector(5);
        for (int i = 0; i < 5; i++) {
            colSum.add((float) 0);
        }

        for (int i = 0; i < fullVec.size(); i++) {
            Vector row = (Vector) fullVec.get(i);
            float sum = 0;
            for (int k = 1; k < row.size() - 1; k++) {
                Object o = row.get(k);
                if (o != null) {
                    sum += (float) o;
                    Object tob = colSum.get(k - 1);
                    if (tob != null) {
                        colSum.setElementAt((float) o + (float) tob, k - 1);
                    }
                }
            }
            dtmFeeBRUP.setValueAt(sum, i, 6);
        }
        int i = 0;
        float total = (float) 0;
        for (Object o : colSum) {
            if (o != null) {
                total += (float) o;
                dtmFee.setValueAt((float) o, i, 1);
            }
            i++;
        }
        dtmFee.setValueAt(total, i, 1);
    }//GEN-LAST:event_feeBRUPTableKeyReleased

    private void feeTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeTableKeyReleased
        Object ob = null;
        float total = 0;
        for (int k = 0; k < 5; k++) {
            ob = null;
            ob = dtmFee.getValueAt(k, 1);
            if (ob != null) {
                float tutFee = ((float) ob);
                total += tutFee;
                tutFee /= dtmFeeBRUP.getRowCount();
                for (int i = 0; i < dtmFeeBRUP.getRowCount(); i++) {
                    dtmFeeBRUP.setValueAt(tutFee, i, k + 1);
                }
            }
        }
        dtmFee.setValueAt(total, 5, 1);
        total /= dtmFeeBRUP.getRowCount();
        for (int i = 0; i < dtmFeeBRUP.getRowCount(); i++) {
            dtmFeeBRUP.setValueAt(total, i, 6);
        }
    }//GEN-LAST:event_feeTableKeyReleased

    private void tfPanltyRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPanltyRateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPanltyRateKeyReleased

    private void tfPanltyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPanltyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPanltyRateActionPerformed

    private void tfClassNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClassNameKeyTyped

    }//GEN-LAST:event_tfClassNameKeyTyped

    private void tfClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClassNameActionPerformed

    private void tfPanltyRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPanltyRateKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b') && (caracter != '.')) {
            evt.consume();
        } else {
            if ((caracter == '.') && tfPanltyRate.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tfPanltyRateKeyTyped

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        InitGui();

    }//GEN-LAST:event_cancleButtonActionPerformed

    private void comBoxPenaltyCycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxPenaltyCycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxPenaltyCycleActionPerformed

    private void fromYearTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromYearTFKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b') && (caracter != '.')) {
            evt.consume();
        }          // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_fromYearTFKeyTyped

    private void fromYearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromYearTFActionPerformed
        updateUsingThisYear();        // TODO add your handling code here:
    }//GEN-LAST:event_fromYearTFActionPerformed

    private void fromYearTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromYearTFFocusLost
        if (fromYearTF.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "Invalid Year");
        }
    }//GEN-LAST:event_fromYearTFFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateUsingThisYear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void monthStudenListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthStudenListItemStateChanged
        UpdateStudentList();
    }//GEN-LAST:event_monthStudenListItemStateChanged

    private void durationTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTFKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTFKeyReleased

    private void durationTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTFKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_durationTFKeyTyped
    public void as() {
//        int x = jSplitPane1.getDividerLocation();
//        System.out.println("x = " + x);
//        if (x == SplitDividerDefault) {
//            jButton1.setText("<");
//            jSplitPane1.setDividerLocation(SplitDividerEnlarged);
//        } else {
//            jButton1.setText(">");
//            jSplitPane1.setDividerLocation(SplitDividerDefault);
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search1;
    private javax.swing.JLabel Search2;
    private javax.swing.JLabel Search3;
    private javax.swing.JLabel Search4;
    private javax.swing.JLabel Search5;
    private javax.swing.JLabel Search6;
    private javax.swing.JPanel StudentList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancleButton;
    private javax.swing.JCheckBox ckBoxEdit;
    private javax.swing.JTable classTable;
    private javax.swing.JComboBox comBoxPenaltyCycle;
    private javax.swing.JComboBox dayOfMonth;
    private javax.swing.JTextField durationTF;
    private javax.swing.JTable feeBRUPTable;
    private javax.swing.JTable feeTable;
    private javax.swing.JTextField fromYearTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JComboBox<String> monthStudenList;
    private javax.swing.JButton newButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tableStudentList;
    private javax.swing.JTextField tfClassName;
    private javax.swing.JTextField tfPanltyRate;
    // End of variables declaration//GEN-END:variables

    private void serachButtonAction() {
        searchData = Utility.searchClasses();
        Vector cols = new Vector();
        cols.addElement("ID");
        cols.addElement("Name");
        cols.addElement("Year");
        cols.addElement("Cycle");
        cols.addElement("Pernalty rate");
        dtmClassTable.setDataVector(searchData, cols);
    }

    private void InitGui() {
        tfClassName.setText("");
        newButton.setEnabled(true);
        fromYearTF.setEditable(false);
        durationTF.setEditable(false);
        tfClassName.setEditable(false);
        saveButton.setEnabled(false);
        tfPanltyRate.setEditable(false);
        tfClassName.setEditable(false);
        ckBoxEdit.setSelected(false);
        ckBoxEdit.setEnabled(true);
        feeTable.setEnabled(false);
        feeBRUPTable.setEnabled(false);
        cancleButton.setEnabled(false);
        saveButton.setEnabled(false);
    }

    private boolean checkOfSave() {
        if (!newButton.isEnabled() || ckBoxEdit.isSelected()) {
            int choice = JOptionPane.showConfirmDialog(null, "Do You Want To Save Details?");
            if (choice == 0) {
                return true;
            } else if (choice == 1) {
                InitGui();
            } else if (choice == 2) {
                InitGui();
            }
            System.out.println(choice);
        }
        return false;
    }

    private void serachActive() {
//        resetData();
        //        cb.setVillage(jTextField3.getText());
//        cb.setPhone_1(jTextField4.getText());
//        cb.setPhone_2(jTextField4.getText());
//        cb.setFatherName(jTextField5.getText());
//        if (jTextField1.getText().length() != 0) {
//            cb.setIdCustomerDetails(Integer.parseInt(jTextField1.getText()));
//        } else {
//            cb.setIdCustomerDetails(0);
//        }
//        searchData = mStudent.customerSearch();
        Vector cols = new Vector();
        cols.addElement("A/C No.");
        cols.addElement("Name");
        cols.addElement("Father Name");
        cols.addElement("Village");
        cols.addElement("Phone_1");
        cols.addElement("Vhone_2");

//        dtm.setDataVector(searchData, cols);
    }

    private void printToPDF() {

        //    int roc = dtm.size(), noc = ((Vector) dtm.elementAt(0)).size();
//        PdfPTable table = new PdfPTable(8);
//        PdfPCell cell = new PdfPCell(new Phrase("ACCOUNT NUMBER :" + mStudent.getAccountNumber()));
//        cell.setColspan(8);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Name :" + mStudent.getName()));
//        cell.setColspan(3);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Ocup./Surname :" + mStudent.getFatherName()));
//        cell.setColspan(3);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Villege  :" + mStudent.getVillage()));
//        cell.setColspan(2);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Phone  :" + mStudent.getPhone_1() + "," + mStudent.getPhone_2()));
//        cell.setColspan(8);
//        table.addCell(cell);
//
//        Vector cols = new Vector();
//        cols.addElement("Sr No.");
//        cols.addElement("Date");
//        cols.addElement("Particulars");
//        cols.addElement("Folio");
//        cols.addElement("Debit");
//        cols.addElement("Credit");
//        cols.addElement("Dr. or Cr.");
//        cols.addElement("Balance");
//
//        for (int i = 0; i < cols.size(); i++) {
//            String stmp = "" + cols.elementAt(i);
//            cell = new PdfPCell(new Phrase(stmp));
//            cell.setColspan(1);
//            table.addCell(cell);
//        }
//        Vector dtm = lb.getDetailsof(mStudent.getAccountNumber());
//
//        for (int i = 0; i < dtm.size(); i++) {
//
//            Vector tv = (Vector) dtm.elementAt(i);
//            for (int j = 0; j < tv.size(); j++) {
//                String stmp = "" + tv.elementAt(j);
//                cell = new PdfPCell(new Phrase(stmp));
//                cell.setColspan(1);
//                table.addCell(cell);
//            }
//        }
//        if (dtm.size() < 60) {
//            for (int i = 0; i < (30 - dtm.size()) * 8; i++) {
//                cell = new PdfPCell(new Phrase(" "));
//                cell.setColspan(1);
//                table.addCell(cell);
//            }
//        }
//        Document document = new Document();
//        try {
//            String fname = mStudent.getAccountNumber();
//            if (mStudent.getAccountNumber().length() == 0) {
//                fname = mStudent.getSrNo() + "";
//            }
//            PdfWriter.getInstance(document, new FileOutputStream("D:\\MAKIMS\\" + fname + ".PDF"));
//            document.open();
//            document.add(table);
//            document.close();
//            JOptionPane.showMessageDialog(null, "Document Printed Sucessfully and Stored.");
//        } catch (Exception ex) {
//            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void clearFeeAndFeeBRUPTable() {
        Vector rowsFee = new Vector();
        Vector colsFee = new Vector();
        colsFee.addElement("Type");
        colsFee.addElement("Amount");
        Vector row1 = new Vector();
        row1.add("Tution Fee");
        rowsFee.add(row1);
        row1 = new Vector();
        row1.add("Library Fee");
        rowsFee.add(row1);
        row1 = new Vector();
        row1.add("Stationary Fee");
        rowsFee.add(row1);
        row1 = new Vector();
        row1.add("Dress Fee");
        rowsFee.add(row1);
        row1 = new Vector();
        row1.add("Misc. Fee");
        rowsFee.add(row1);
        row1 = new Vector();
        row1.add("Total Fee");
        rowsFee.add(row1);
        dtmFee.setDataVector(rowsFee, colsFee);
        Vector colsFeeBRUP = new Vector();
        colsFeeBRUP.addElement("Month");
        colsFeeBRUP.add("Tution Fee");
        colsFeeBRUP.add("Library Fee");
        colsFeeBRUP.add("Stationary Fee");
        colsFeeBRUP.add("Dress Fee");
        colsFeeBRUP.add("Misc. Fee");
        colsFeeBRUP.add("Total Fee");

        start.set(Calendar.DATE, 1);
        start.set(Calendar.MONTH, Utility.getMonthValueFromMonthName((String) monthCB.getSelectedItem()));
        Calendar fromDate = Calendar.getInstance();
        fromDate.setTime(start.getTime());
        Vector rowsFeeBRUP = new Vector();

        for (; fromDate.before(end); fromDate.add(Calendar.MONTH, 1)) {
            Vector row = new Vector();
            String month = Utility.getMonthStrFromNum(fromDate.get(Calendar.MONTH)) + "~" + fromDate.get(Calendar.YEAR);
            row.add(month);
            rowsFeeBRUP.add(row);
        }
        dtmFeeBRUP.setDataVector(rowsFeeBRUP, colsFeeBRUP);

    }

    private int saveModifyClass() {
        boolean isEdit = ckBoxEdit.isSelected();
        if (isEdit) {
            if (mClass == null) {
                return -1;
            }
        }
        if (ckBoxEdit.isSelected() || !newButton.isEnabled()) {
            String str = tfClassName.getText();
            if (str.length() != 0) {
                Session ses = HibernateUtil.getSessionFactory().openSession();
                CLASS lClass = null;
                if (isEdit) {
                    lClass = Utility.getClassWithID(mClass.getIdClass(), ses);
                } else {
                    lClass = new CLASS();
                }
                lClass.setNameOfClass(str);
                lClass.setFromYear(start.getTime());
                lClass.setToYear(end.getTime());
                lClass.setDueDay(dayOfMonth.getSelectedIndex());
                lClass.setPenaltyCycle(comBoxPenaltyCycle.getSelectedIndex());
                str = tfPanltyRate.getText();
                if (str.length() > 0) {
                    lClass.setLateFeePercent(Float.parseFloat(str));
                }
                lClass.setLastUpdate(new Date());
                FEEDETAILS lfeeDTLS = null;
                if (isEdit) {
                    lfeeDTLS = Utility.getFeeDTLSWithID(mClass.getFeeDetails().getIdFeeDetails(), ses);
                } else {
                    lfeeDTLS = new FEEDETAILS();
                }
                Vector feeDV = dtmFee.getDataVector();
                Object lTmp = ((Vector) feeDV.get(0)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setTutionFee((float) lTmp);
                }
                lTmp = ((Vector) feeDV.get(1)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setLibraryFee((float) lTmp);
                }
                lTmp = ((Vector) feeDV.get(2)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setStationaryFee((float) lTmp);
                }
                lTmp = ((Vector) feeDV.get(3)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setDressFee((float) lTmp);
                }
                lTmp = ((Vector) feeDV.get(4)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setMiscFee((float) lTmp);
                }
                lTmp = ((Vector) feeDV.get(5)).get(1);
                if (lTmp != null) {
                    lfeeDTLS.setTotalFee((float) lTmp);
                }
                ses.beginTransaction();
                try {
                    if (isEdit) {
                        ses.saveOrUpdate(lfeeDTLS);
                        ses.saveOrUpdate(lClass);

                    } else {
                        ses.save(lfeeDTLS);
                        lClass.setFeeDetails(lfeeDTLS);
                        ses.save(lClass);
                    }
                    DefaultTableModel dtmFeeBRUPTable = (DefaultTableModel) feeBRUPTable.getModel();
                    Vector feeBRDV = dtmFeeBRUPTable.getDataVector();
                    if (feeBRDV != null) {

                        Calendar dueDate = Calendar.getInstance();
                        dueDate.setTime(start.getTime());

                        Calendar classDate = Calendar.getInstance();
                        classDate.setTime(dueDate.getTime());
                        dueDate.set(Calendar.DATE, dayOfMonth.getSelectedIndex());

                        for (Object obj : feeBRDV) {
                            Vector lRow = (Vector) obj;
                            if (lRow != null) {
                                FEEBREAKUP lFeeBRUP = null;
                                if (isEdit) {
                                    lFeeBRUP = Utility.getFeeBRUPWithFeeDetailsIDAndMonth(lfeeDTLS.getIdFeeDetails(), classDate.get(Calendar.MONTH), ses);
                                    if (lFeeBRUP == null) {
                                        lFeeBRUP = new FEEBREAKUP();
                                    }
                                } else {
                                    lFeeBRUP = new FEEBREAKUP();
                                }
                                lFeeBRUP.setMonth(classDate.getTime());
                                if (null != lRow.get(1)) {
                                    lFeeBRUP.setTutionFee((float) lRow.get(1));
                                }
                                if (null != lRow.get(2)) {
                                    lFeeBRUP.setLibraryFee((float) lRow.get(2));
                                }
                                if (null != lRow.get(3)) {
                                    lFeeBRUP.setStationaryFee((float) lRow.get(3));
                                }
                                if (null != lRow.get(4)) {
                                    lFeeBRUP.setDressFee((float) lRow.get(4));
                                }
                                if (null != lRow.get(5)) {
                                    lFeeBRUP.setMiscFee((float) lRow.get(5));
                                }
                                if (null != lRow.get(6)) {
                                    lFeeBRUP.setTotalFee((float) lRow.get(6));
                                }
                                lFeeBRUP.setIdFeeDTLS(lfeeDTLS);
                                lFeeBRUP.setDueDate(dueDate.getTime());

                                ses.saveOrUpdate(lFeeBRUP);
                            }
                            dueDate.add(Calendar.MONTH, 1);
                            classDate.add(Calendar.MONTH, 1);

                        }
                    }
                } catch (Exception e) {
                    ses.getTransaction().rollback();
                    e.printStackTrace();
                    return -2;
                }
                ses.getTransaction().commit();
                ses.close();
                return 1;
            }
        } else {
            return -1;
        }
        return -1;
    }

    private void updateClassForm() {
        if (mClass != null) {
            tfClassName.setText(mClass.getNameOfClass());
            tfPanltyRate.setText(mClass.getLateFeePercent() + "");
            comBoxPenaltyCycle.setSelectedIndex(mClass.getPenaltyCycle());
            dayOfMonth.setSelectedIndex(mClass.getDueDay());
            if (mClass.getFeeDetails() != null) {
                dtmFee.setValueAt(mClass.getFeeDetails().getTutionFee(), 0, 1);
                dtmFee.setValueAt(mClass.getFeeDetails().getLibraryFee(), 1, 1);
                dtmFee.setValueAt(mClass.getFeeDetails().getStationaryFee(), 2, 1);
                dtmFee.setValueAt(mClass.getFeeDetails().getDressFee(), 3, 1);
                dtmFee.setValueAt(mClass.getFeeDetails().getMiscFee(), 4, 1);
                dtmFee.setValueAt(mClass.getFeeDetails().getTotalFee(), 5, 1);
            } else {
                dtmFee.setValueAt(0, 0, 1);
                dtmFee.setValueAt(0, 1, 1);
                dtmFee.setValueAt(0, 2, 1);
                dtmFee.setValueAt(0, 3, 1);
                dtmFee.setValueAt(0, 4, 1);
                dtmFee.setValueAt(0, 5, 1);
            }
        }
    }

    private void updateUsingThisYear() {
        String fromYr = fromYearTF.getText();
        String duration = durationTF.getText();
        if (fromYr.length() > 3 && duration.length() > 0) {
            String mon = (String) monthCB.getSelectedItem();
            start.set(Calendar.MONTH, Utility.getMonthValueFromMonthName(mon));
            start.set(Calendar.YEAR, Integer.parseInt(fromYr));
            end.setTime(start.getTime());
            end.add(Calendar.MONTH, Integer.parseInt(duration));
        }
        clearFeeAndFeeBRUPTable();
    }

    private void UpdateStudentList() {
        if (mClass != null) {
            String mon = (String) monthStudenList.getSelectedItem();
            Vector colsStudentList = new Vector();
            colsStudentList.add("SR NO");
            colsStudentList.add("SSO");
            colsStudentList.add("Name");
            colsStudentList.add("Father Name");
            colsStudentList.add("Total ");
            colsStudentList.add("Penalty");
            colsStudentList.add("Paid");
            colsStudentList.add("Due");
            Vector rows = new Vector();
            DefaultTableModel dtmStudentList = (DefaultTableModel) tableStudentList.getModel();
            Session ses = HibernateUtil.getSessionFactory().openSession();
            try {
                List studens = Utility.getStudentWithClassID(mClass.getIdClass(), ses);
                for (Object o : studens) {
                    Vector row = new Vector();
                    STUDENT s = (STUDENT) o;
                    if (s != null) {
                        int imon = Utility.getMonthValueFromMonthName(mon);
                        FEEBREAKUP frb = Utility.getFeeBRUPWithFeeDetailsIDAndMonth(
                                mClass.getFeeDetails().getIdFeeDetails(), imon, ses);
                        STUDENTLEDGER sld = Utility.getStudentLDGRWithFeeBRUPIdAndSTDNTID(s.getIdStudent(), frb.getIdFeeBRUP(), ses);
                        if (sld != null) {
                            row.add(s.getIdStudent());
                            row.add(s.getSSO());
                            String name = s.getFIRST_NAME();
                            if (s.getLAST_NAME() != null) {
                                name += s.getLAST_NAME();
                            }
                            row.add(name);
                            row.add(s.getFATHERS_NAME());
                            float totalFee = frb.getTotalFee();
                            double penalty = sld.getPENALTY();
                            Date dueDate = frb.getDueDate();
                            if (dueDate != null) {
                                Calendar du = Calendar.getInstance();
                                du.setTime(dueDate);
                                Calendar cu = Calendar.getInstance();
                                cu.setTime(new Date());
                                int diffYear = cu.get(Calendar.YEAR) - du.get(Calendar.YEAR);
                                int diffMonth = diffYear * 12 + cu.get(Calendar.MONTH) - du.get(Calendar.MONTH);
                                if (mClass.getPenaltyCycle() == 0) {
                                    if (diffMonth > 0) {
                                        penalty = (double) totalFee
                                                * Math.pow((1.0 + ((double) mClass.getLateFeePercent() / 100.0)), diffMonth);
                                        penalty = penalty - totalFee;
                                    }
                                }
                            }
                            penalty = Utility.roundToDecimal(penalty);
                            float grandTotla = totalFee + (float) penalty;
                            float paid = sld.getAMT_TO_PAID();
                            float due = grandTotla - paid;
                            row.add(totalFee);
                            row.add(penalty);
                            row.add(paid);
                            row.add(due);

                        }
                    }
                    rows.add(row);
                }

            } catch (Exception e) {
            } finally {
                ses.close();
            }
//        List studens = Utility.get
            dtmStudentList.setDataVector(rows, colsStudentList);
        } else {

        }
    }

    private void SaveButtonAction() {
        int lRet = saveModifyClass();
        if (lRet == 1) {
            JOptionPane.showMessageDialog(null, "Class Added Succesfully..");
            newButton.setEnabled(true);
            ckBoxEdit.setSelected(false);
            ckBoxEdit.setEnabled(true);
            tfClassName.setEditable(false);
            tfPanltyRate.setEditable(false);
            feeTable.setEnabled(false);
            feeBRUPTable.setEnabled(false);
            cancleButton.setEnabled(false);
            saveButton.setEnabled(false);
            serachButtonAction();
        } else {
            JOptionPane.showMessageDialog(null, "Error Occured :" + lRet);
        }
    }
}
