/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmtv0.UI;

import Hibernate.Entity.ADDRESS;
import Hibernate.Entity.STUDENT;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jmtv0.pkg0.Utility.Utility;
import org.h2.util.New;
import org.hibernate.Session;
import Splash.*;
import static Splash.Splash.splashProgress;
import static Splash.Splash.splashText;

/**
 *
 * @author lrmakode
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static int width = 0;
    public static int hight = 0;
    private ButtonGroup plafGroup = null;
    Image img = (new ImageIcon(getClass().getResource("/img/icon.png"))).getImage();

    public Main() {
        initComponents();
        //updateLookAndFeel(GUIProperties.PLAF_TEXTURE);
//        Reminder r = Utility.getReminderWithDate(mainSession, new Date());

        //setIconImage(image);
        int lRet = InitSystem();

        if (Splash.mySplash != null) // check if we really had a spash screen
        {
            Splash.mySplash.close();   // we're done with it
        }
        if (lRet != Utility.UTIL_SUCESS) {
            JOptionPane.showMessageDialog(null, "Utility Initalization Failed(" + lRet + ").. contact lokesh makode..");
            Utility.terminate();
        }
        super.setIconImage(img);
        openHomePage();

//        jSplitPane1.setDividerLocation(SplitDividerDefault);
//        Looks = UIManager.getInstalledLookAndFeels();
//        Dimension dm = Toolkit.getDefaultToolkit().getScreenSize();
//        setBounds(0, 0, dm.width, dm.height - 40);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        width = this.getWidth();
        hight = this.getHeight();
    }
//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        HomeB = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        VendorB = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        ProductB2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        ProductB1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ProductB = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        ProductB3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        bkupButton = new javax.swing.JMenuItem();
        UpdateBalance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMTv0.3");
        setIconImage(img);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jToolBar1.setRollover(true);

        jLabel2.setText("    ");
        jToolBar1.add(jLabel2);

        HomeB.setForeground(new java.awt.Color(3, 6, 23));
        HomeB.setText("Home");
        HomeB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HomeB.setFocusable(false);
        HomeB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBActionPerformed(evt);
            }
        });
        jToolBar1.add(HomeB);
        jToolBar1.add(jSeparator4);

        jButton1.setText("Student");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator6);

        VendorB.setText("Classes");
        VendorB.setFocusable(false);
        VendorB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VendorB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        VendorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorBActionPerformed(evt);
            }
        });
        jToolBar1.add(VendorB);
        jToolBar1.add(jSeparator3);

        ProductB2.setText("Bus Fare");
        ProductB2.setFocusable(false);
        ProductB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProductB2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProductB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductB2ActionPerformed(evt);
            }
        });
        jToolBar1.add(ProductB2);
        jToolBar1.add(jSeparator7);

        ProductB1.setText("Student Registration");
        ProductB1.setFocusable(false);
        ProductB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProductB1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProductB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductB1ActionPerformed(evt);
            }
        });
        jToolBar1.add(ProductB1);
        jToolBar1.add(jSeparator5);

        ProductB.setText("Fee Payment");
        ProductB.setFocusable(false);
        ProductB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProductB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProductB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductBActionPerformed(evt);
            }
        });
        jToolBar1.add(ProductB);
        jToolBar1.add(jSeparator8);

        ProductB3.setText("Fees Status");
        ProductB3.setFocusable(false);
        ProductB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProductB3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProductB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductB3ActionPerformed(evt);
            }
        });
        jToolBar1.add(ProductB3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(TabbedPane, java.awt.BorderLayout.CENTER);

        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator1);

        jButton2.setText("Add New Tab");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jToolBar2.add(jButton2);
        jToolBar2.add(jSeparator2);

        jButton4.setText("Close Active Tab");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jPanel3.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, "card3");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu9.setText("EDIT");

        jMenuItem39.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem39.setText("New Tab");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem39);

        jMenuItem40.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem40.setText("Close Current Tab");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem40);

        jMenuBar1.add(jMenu9);

        jMenu2.setText("STUDENT");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Student Registration");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Student List");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("CLASS");

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setText("Class List");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("FEE");

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Fee Payment");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenu5.setText("Purchase Order List");

        jMenuItem18.setText("Recent Orders");
        jMenu5.add(jMenuItem18);

        jMenuItem19.setText("Open Orders");
        jMenu5.add(jMenuItem19);

        jMenuItem20.setText("Invoiced Orders");
        jMenu5.add(jMenuItem20);

        jMenuItem21.setText("Paid Orders");
        jMenu5.add(jMenuItem21);

        jMenu3.add(jMenu5);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setText("New Vendor");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("SETTINGS");

        bkupButton.setText("Take Backup");
        bkupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkupButtonActionPerformed(evt);
            }
        });
        jMenu1.add(bkupButton);

        UpdateBalance.setText("Update Balance");
        UpdateBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBalanceActionPerformed(evt);
            }
        });
        jMenu1.add(UpdateBalance);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBActionPerformed
        openNewTab();
        openHomePage();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        openNewTab();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        openNewTab();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        closeActiveTab();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        closeActiveTab();
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        openNewTab();
        try {
            OpenStudentRegistrationForm();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        addClasses();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(null, "Good Bye");
        // TODO add your handling code here:
        Utility.terminate();
    }//GEN-LAST:event_formWindowClosing

    private void VendorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendorBActionPerformed
        openNewTab();
        addClasses();
    }//GEN-LAST:event_VendorBActionPerformed

    private void ProductBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductBActionPerformed
        openNewTab();
        OpenFeePayemntForm();
    }//GEN-LAST:event_ProductBActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        openNewTab();
        try {
            OpenFeePayemntForm();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openNewTab();
        addNewStudent();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProductB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductB1ActionPerformed
        openNewTab();
        try {
            OpenStudentRegistrationForm();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductB1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openNewTab();
        try {
            addNewStudent();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        openNewTab();
        try {
            addClasses();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void bkupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkupButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File out = fileChooser.getSelectedFile();
            try {
                File in = new File("C:\\JMT\\DB\\JMTFINAL.mv.db");
//                Utility.copyFileUsingStream(in,out);
                Files.copy(in.toPath(), out.toPath());

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error While Taking Backup ");
            }
            // save to file
        }
    }//GEN-LAST:event_bkupButtonActionPerformed

    private void ProductB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductB2ActionPerformed
        openNewTab();
        addBusFee();
    }//GEN-LAST:event_ProductB2ActionPerformed

    private void ProductB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductB3ActionPerformed
        openNewTab();
        OpenFeeStatusForm();
    }//GEN-LAST:event_ProductB3ActionPerformed

    private void UpdateBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBalanceActionPerformed
        Utility.updateBalance();
    }//GEN-LAST:event_UpdateBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Splash.splashInit();
        splashText("Initalizing Database...");     // tell the user what initialization task is being done
        splashProgress(87);            // give them an idea how much we have completed

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    javax.swing.UIManager.setLookAndFeel(new AeroLookAndFeel());
                    break;
                }
            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);;
            }
        });
    }

    private void openHomePage() {
//        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
//        System.out.println(jp.getClass());
//        if (jp != null) {
//            if (jp.getClass() != HomePage.class) {
//                int x = TabbedPane.getSelectedIndex();
////                System.out.println(x);
//                if (x != -1) {
//                    TabbedPane.remove(x);
//                }
//                TabbedPane.add(new HomePage(), x);
//                x = jTabbedPane2.getSelectedIndex();
//                TabbedPane.setTitleAt(x, "Home Page");
//                TabbedPane.setSelectedIndex(x);
//                TabbedPane.setTabComponentAt(TabbedPane.getSelectedIndex(), new ButtonTabComponent(TabbedPane));
//            }
//        } else {
//            int x = TabbedPane.getSelectedIndex();
//            TabbedPane.add(new HomePage(), x);
//            x = TabbedPane.getSelectedIndex();
//            TabbedPane.setTitleAt(x, "Home Page");
//            TabbedPane.setSelectedIndex(x);
////        
//        }
//
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeB;
    private javax.swing.JButton ProductB;
    private javax.swing.JButton ProductB1;
    private javax.swing.JButton ProductB2;
    private javax.swing.JButton ProductB3;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JMenuItem UpdateBalance;
    private javax.swing.JButton VendorB;
    private javax.swing.JMenuItem bkupButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
    UIManager.LookAndFeelInfo Looks[];

    private void openNewTab() {
        TabbedPane.add("New Tab", new JPanel());
        TabbedPane.setSelectedIndex(TabbedPane.getTabCount() - 1);
    }

    private void closeActiveTab() {
        if (TabbedPane.getTabCount() > 1) {
            TabbedPane.remove(TabbedPane.getSelectedIndex());
        }
    }

    private void addNewStudent() {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != StudentList.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new StudentList(), x);
                TabbedPane.setTitleAt(x, "New Student");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new StudentList(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "New Student");
            TabbedPane.setSelectedIndex(x);
        }
    }

    private void OpenStudentRegistrationForm() throws IOException {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != StudentRegistration.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new StudentRegistration(), x);
                TabbedPane.setTitleAt(x, "Student Registration Form");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new StudentRegistration(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Student Registration Form");
            TabbedPane.setSelectedIndex(x);

        }
//        TabbedPane.setTabComponentAt(TabbedPane.getSelectedIndex(), new ButtonTabComponent(TabbedPane));
    }

    private void openPO() throws IOException {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
//            if (jp.getClass() != NewPO.class) {
//                int x = TabbedPane.getSelectedIndex();
//                if (x != -1) {
//                    TabbedPane.remove(x);
//                }
//                TabbedPane.add(new NewPO(), x);
//                TabbedPane.setTitleAt(x, "Purchase Order");
//                TabbedPane.setSelectedIndex(x);
//            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
//            TabbedPane.add(new NewPO(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Purchase Order");
            TabbedPane.setSelectedIndex(x);

        }
//        TabbedPane.setTabComponentAt(TabbedPane.getSelectedIndex(), new ButtonTabComponent(TabbedPane));
    }

    private void addClasses() {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != ClassesList.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new ClassesList(), x);
                TabbedPane.setTitleAt(x, "Classes List");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new ClassesList(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Classes List");
            TabbedPane.setSelectedIndex(x);
        }
    }

    private void OpenFeePayemntForm() {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != FeeSubmissionForm.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new FeeSubmissionForm(), x);
                TabbedPane.setTitleAt(x, "Fee Payment Form");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new FeeSubmissionForm(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Fee Payment Form");
            TabbedPane.setSelectedIndex(x);
        }
//        TabbedPane.setTabComponentAt(TabbedPane.getSelectedIndex(), new ButtonTabComponent(TabbedPane));
    }

//    private void newPO() {
//        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
//        if (jp != null) {
//            if (jp.getClass() != NewCustomer.class) {
//                int x = TabbedPane.getSelectedIndex();
//                if (x != -1) {
//                    TabbedPane.remove(x);
//                }
//                TabbedPane.add(new NewCustomer(), x);
//                TabbedPane.setTitleAt(x,"Customer");
//                TabbedPane.setSelectedIndex(x);
//            }
//        } else {
//            int x = TabbedPane.getSelectedIndex();
//            System.out.println(x);
//            TabbedPane.add(new NewCustomer(), x);
//            x = TabbedPane.getSelectedIndex();
//            TabbedPane.setTitleAt(x, "Vendor");
//            TabbedPane.setSelectedIndex(x);
//
//        }
//        TabbedPane.setTabComponentAt(TabbedPane.getSelectedIndex(), new ButtonTabComponent(TabbedPane));
//    }
    private void updateLookAndFeel(String PLAF_METAL) {
        try {
            UIManager.setLookAndFeel(PLAF_METAL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    private int InitSystem() {
        return Utility.init();
    }

    private void addBusFee() {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != BusList.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new BusList(), x);
                TabbedPane.setTitleAt(x, "Bus Fee");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new BusList(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Bus Fee");
            TabbedPane.setSelectedIndex(x);
        }
    }

    private void OpenFeeStatusForm() {
        JPanel jp = (JPanel) TabbedPane.getSelectedComponent();
        if (jp != null) {
            if (jp.getClass() != FeeStatus.class) {
                int x = TabbedPane.getSelectedIndex();
                if (x != -1) {
                    TabbedPane.remove(x);
                }
                TabbedPane.add(new FeeStatus(), x);
                TabbedPane.setTitleAt(x, "Fee Status");
                TabbedPane.setSelectedIndex(x);
            }
        } else {
            int x = TabbedPane.getSelectedIndex();
            System.out.println(x);
            TabbedPane.add(new FeeStatus(), x);
            x = TabbedPane.getSelectedIndex();
            TabbedPane.setTitleAt(x, "Fee Payment");
            TabbedPane.setSelectedIndex(x);
        }
    }
}
