/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmtv0.UI;

import jmtv0.pkg0.Utility.HibernateUtil;
import Hibernate.Entity.ADDRESS;
import Hibernate.Entity.BUSFEE;
import Hibernate.Entity.CLASS;
import Hibernate.Entity.STUDENT;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import jmtv0.pkg0.Utility.ComboBoxSearchEnable;
import jmtv0.pkg0.Utility.Utility;
import org.hibernate.Session;

/**
 *
 * @author Lokesh
 */
public class StudentList extends javax.swing.JPanel {

    private static final int SplitDividerDefault = 500;
    private static final int SplitDividerEnlarged = 400;
    private STUDENT mStudent = null;
//    private ADDRESS mStudent.getStdntAddress() = null;
//    private LedgerBean lb = null;
    private Vector searchData = null;
    private DefaultTableModel dtm = null;
    private JFrame jf = null;

    /**
     * Creates new form SalesQuote
     */
    public StudentList() {
        initComponents();
        dtm = (DefaultTableModel) jTable2.getModel();
        mStudent = new STUDENT();
        jSplitPane1.setDividerLocation(SplitDividerEnlarged);
        jf = new JFrame();
        jf.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setAllItemsEditableFalse();
        jDateChooser1.setDate(new Date());
        serachButtonAction();
        fillComboBoxes();
    }

    private void fillComboBoxes() {
        Vector cities = Utility.getVectorOfCitiesFromBUSFEE();
        Vector states = Utility.getVectorOfStatesFromAddress();
        Vector country = Utility.getVectorOfCountryFromAddress();
        Vector street = Utility.getVectorOfStreetsFromAddress();
        Vector classes = Utility.getVectorOfClasses("Not Enrolled");
        cbClass.setModel(new DefaultComboBoxModel(classes));
        comBoxAddress.setModel(new DefaultComboBoxModel(street));
        comBoxState.setModel(new DefaultComboBoxModel(states));
        comBoxCity.setModel(new DefaultComboBoxModel(cities));
        comBoxCountry.setModel(new DefaultComboBoxModel(country));
        comBoxAddress.setEditable(true);
        comBoxCity.setEditable(true);
        comBoxCountry.setEditable(true);
        comBoxState.setEditable(true);
        ComboBoxSearchEnable s17NonStrict = new ComboBoxSearchEnable(comBoxCountry);
        ComboBoxSearchEnable s17NonStrict1 = new ComboBoxSearchEnable(comBoxCity);
        ComboBoxSearchEnable s17NonStrict2 = new ComboBoxSearchEnable(comBoxAddress);
        ComboBoxSearchEnable s17NonStrict3 = new ComboBoxSearchEnable(comBoxState);

        ((JTextField) comBoxAddress.getEditor().getEditorComponent()).setText("");
        ((JTextField) comBoxCity.getEditor().getEditorComponent()).setText("");
        ((JTextField) comBoxCountry.getEditor().getEditorComponent()).setText("");
        ((JTextField) comBoxState.getEditor().getEditorComponent()).setText("");
        tfPinCode.setText("");
        taRemarks.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        ckBoxEdit = new javax.swing.JCheckBox();
        bPrint = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfFathersName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfStudentFName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfCell1 = new javax.swing.JTextField();
        tfCell2 = new javax.swing.JTextField();
        tfSSO = new javax.swing.JTextField();
        tfStudentMName = new javax.swing.JTextField();
        tfStudentLName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comBoxState = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comBoxCountry = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taRemarks = new javax.swing.JTextArea();
        comBoxCity = new javax.swing.JComboBox();
        tfPinCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comBoxAddress = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbClass = new javax.swing.JComboBox();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel53 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfAadharNumber = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        creditRB = new javax.swing.JRadioButton();
        debitRB = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Search1 = new javax.swing.JLabel();
        Search2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Search3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Search4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        Search5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Search6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        newButton.setText("New");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newButton);

        bSave.setText("Save");
        bSave.setFocusable(false);
        bSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(bSave);

        ckBoxEdit.setText("EDIT");
        ckBoxEdit.setFocusable(false);
        ckBoxEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ckBoxEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ckBoxEdit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckBoxEditItemStateChanged(evt);
            }
        });
        jToolBar1.add(ckBoxEdit);

        bPrint.setText("Print");
        bPrint.setEnabled(false);
        bPrint.setFocusable(false);
        bPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(bPrint);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setVerifyInputWhenFocusTarget(false);

        tfFathersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFathersNameActionPerformed(evt);
            }
        });

        jLabel25.setText("Name");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tfStudentFName.setEditable(false);

        jLabel30.setText("Father's Name");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel33.setText("Cell Number");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel35.setText("Tel #");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tfSSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSSOActionPerformed(evt);
            }
        });
        tfSSO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSSOKeyTyped(evt);
            }
        });

        tfStudentMName.setEditable(false);
        tfStudentMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentMNameActionPerformed(evt);
            }
        });
        tfStudentMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfStudentMNameKeyReleased(evt);
            }
        });

        tfStudentLName.setEditable(false);
        tfStudentLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentLNameActionPerformed(evt);
            }
        });
        tfStudentLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfStudentLNameKeyReleased(evt);
            }
        });

        jLabel28.setText("First");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel29.setText("Middle");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel51.setText("Last");
        jLabel51.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel52.setText("SSO");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setText("Address");

        jLabel9.setText("Street");

        comBoxState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comBoxStateMouseEntered(evt);
            }
        });
        comBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxStateActionPerformed(evt);
            }
        });

        jLabel10.setText("City");

        jLabel1.setText("Postal Code");

        comBoxCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCountryActionPerformed(evt);
            }
        });

        jLabel12.setText("Remarks");

        taRemarks.setColumns(20);
        taRemarks.setRows(5);
        jScrollPane5.setViewportView(taRemarks);

        comBoxCity.setEditable(true);
        comBoxCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comBoxCityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comBoxCityMouseEntered(evt);
            }
        });
        comBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCityActionPerformed(evt);
            }
        });
        comBoxCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comBoxCityKeyTyped(evt);
            }
        });

        tfPinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPinCodeActionPerformed(evt);
            }
        });
        tfPinCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPinCodeKeyTyped(evt);
            }
        });

        jLabel13.setText("Country");

        jLabel14.setText("State");

        comBoxAddress.setEditable(true);
        comBoxAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comBoxAddressMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comBoxAddressMouseEntered(evt);
            }
        });
        comBoxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxAddressActionPerformed(evt);
            }
        });
        comBoxAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comBoxAddressKeyTyped(evt);
            }
        });

        jLabel11.setText("Class");

        cbClass.setEnabled(false);

        dob.setEnabled(false);

        jLabel53.setText("DOB");
        jLabel53.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel31.setText("Aadhar No.#");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tfAadharNumber.setEditable(false);
        tfAadharNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAadharNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(tfStudentFName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(tfStudentMName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(tfStudentLName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 6, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(tfSSO, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbClass, 0, 191, Short.MAX_VALUE)
                                    .addComponent(tfAadharNumber)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfFathersName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCell1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCell2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(comBoxAddress, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comBoxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPinCode))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(412, 412, 412))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(113, 113, 113)))
                .addGap(1561, 1561, 1561))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel11)
                    .addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentFName)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentMName)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentLName)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFathersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCell1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tfCell2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(comBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tfPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(comBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Customer Info", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel8.setVerifyInputWhenFocusTarget(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel26.setText("!           ");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel26, gridBagConstraints);

        jLabel27.setText("Carrier");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel27, gridBagConstraints);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Specified" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jComboBox9, gridBagConstraints);

        jLabel44.setText("Default Location");
        jLabel44.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel44, gridBagConstraints);

        jLabel46.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel46.setText("Prefrence");
        jLabel46.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jLabel46, gridBagConstraints);

        jLabel47.setText("Card Type");
        jLabel47.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel47, gridBagConstraints);

        jLabel48.setText("Card Number");
        jLabel48.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel48, gridBagConstraints);

        jLabel49.setText("Expiry Date");
        jLabel49.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel49, gridBagConstraints);

        jLabel50.setText("Security Code");
        jLabel50.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel50, gridBagConstraints);

        jLabel54.setText(" ");
        jLabel54.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel54, gridBagConstraints);

        jLabel55.setText(" ");
        jLabel55.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel55, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jTextField21, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jTextField22, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jTextField23, gridBagConstraints);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Specified" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jComboBox11, gridBagConstraints);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Specified" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jComboBox12, gridBagConstraints);

        jLabel58.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel58.setText("Credit Card");
        jLabel58.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jLabel58, gridBagConstraints);

        jLabel59.setText("           ");
        jLabel59.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jLabel59, gridBagConstraints);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Specified" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(jComboBox13, gridBagConstraints);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Specified" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        jPanel8.add(jComboBox14, gridBagConstraints);

        jLabel43.setText("Payment Method");
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel43, gridBagConstraints);

        jLabel45.setText("Default Sales Rep");
        jLabel45.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel8.add(jLabel45, gridBagConstraints);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Extra Info", jPanel4);

        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Date", "Particulars", "Folio", "Debit", "Credit", "DrorCr", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jPanel2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jTextField6.setColumns(15);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jTextField6, gridBagConstraints);

        jLabel2.setText("Amount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabel2, gridBagConstraints);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jTextField7, gridBagConstraints);

        jLabel3.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Particular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel9.add(jLabel4, gridBagConstraints);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jTextField8, gridBagConstraints);

        jLabel5.setText("Folio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabel6, gridBagConstraints);

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jButton8, gridBagConstraints);

        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel9.add(jButton9, gridBagConstraints);

        jLabel7.setText("Dr or Cr.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabel7, gridBagConstraints);

        jTextField20.setColumns(15);
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jTextField20, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 60;
        jPanel9.add(jDateChooser1, gridBagConstraints);

        buttonGroup1.add(creditRB);
        creditRB.setText("Credit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel9.add(creditRB, gridBagConstraints);

        buttonGroup1.add(debitRB);
        debitRB.setText("Debit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel9.add(debitRB, gridBagConstraints);

        jPanel2.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Ledger", jPanel2);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel6FocusGained(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        Search1.setText("A/C Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search1, gridBagConstraints);

        Search2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        Search2.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel6.add(Search2, gridBagConstraints);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField1, gridBagConstraints);

        Search3.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search3, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField2, gridBagConstraints);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField3, gridBagConstraints);

        Search4.setText("Village");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search4, gridBagConstraints);

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel6.add(jButton6, gridBagConstraints);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSO", "Name", "Last N.", "Father N.", "Village", "Cell", "Tell#", "Sr No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField4, gridBagConstraints);

        Search5.setText("Phone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(Search5, gridBagConstraints);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField5, gridBagConstraints);

        Search6.setText("Ocu./LastName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel6.add(Search6, gridBagConstraints);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel5);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        serachButtonAction();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        checkOfSave();

        serachButtonAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        checkOfSave();
        serachButtonAction();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (checkOfSave()) {
            Session ses = HibernateUtil.getSessionFactory().openSession();
            ckBoxEdit.setSelected(false);
            int ids = jTable2.convertRowIndexToModel(jTable2.getSelectedRow());
            if (dtm.getValueAt(ids, 7) != null) {
                mStudent = Utility.getStudentWithID((int) dtm.getValueAt(ids, 7), ses);
                updateStudentsDTLS();
                updateCustomerLadger();
                newButton.setEnabled(true);
            }
            ses.close();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        addModifyVendorDetails();
        serachButtonAction();// TODO add your handling code here:
    }//GEN-LAST:event_bSaveActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        newButton.setEnabled(false);
        checkOfSave();
        ckBoxEdit.setSelected(true);
        mStudent = new STUDENT();
        mStudent.setStdntAddress(new ADDRESS());
        updateStudentsDTLS();
        fillComboBoxes();
    }//GEN-LAST:event_newButtonActionPerformed

    private void ckBoxEditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckBoxEditItemStateChanged
        if (ckBoxEdit.isSelected()) {
            setAllItemsEditableTrue();
            newButton.setEnabled(false);
        } else {
            setAllItemsEditableFalse();
            newButton.setEnabled(true);
        }
    }//GEN-LAST:event_ckBoxEditItemStateChanged

    private void jPanel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6FocusGained

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        checkOfSave();
        serachButtonAction();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed

        printToPDF();
        // TODO add your handling code here:
    }//GEN-LAST:event_bPrintActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b') && (caracter != '.')) {
            evt.consume();
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b') && (caracter != '.')) {
            evt.consume();
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
//        jTextField9.setText("");
//        jComboBox1.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Date dat = jDateChooser1.getDate();
//        lb.setDate(dat.getDate() + "." + (dat.getMonth() + 1) + "." + (dat.getYear() + 1900));
//        lb.setParticulars(jTextField8.getText());
//        lb.setFolio(jTextField7.getText());
//        int x = 0;
//        if (debitRB.isSelected()) {
//            x = 1;
//        } else if (creditRB.isSelected()) {
//            x = 2;
//        }
//
//        if (x == 0) {
//            JOptionPane.showMessageDialog(null, "Please Select Type of Transaction and Enter Amount..");
//        } else if (x == 1) {
//            if (jTextField6.getText().length() == 0 || jTextField6.getText().endsWith(".")) {
//                JOptionPane.showMessageDialog(null, "Please  Enter Correct Amount..");
//            } else {
//                lb.setDebit(Float.parseFloat(jTextField6.getText()));
//                float bal = lb.getlatestBalance("VNDR"+mStudent.getIdVendorDetails());
//                lb.setBalance(bal + lb.getDebit());
//                lb.setCredit(0);
//                lb.setAccountNumber("VNDR"+mStudent.getIdVendorDetails());
//                System.out.println(lb.getBalance() + " lok");
//                if (lb.addToLadger()) {
//                    //JOptionPane.showMessageDialog(null, "Added Successfully");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Error  Ouccured");
//                }
//            }
//        } else if (x == 2) {
//            if (jTextField6.getText().length() == 0 || jTextField6.getText().endsWith(".")) {
//                JOptionPane.showMessageDialog(null, "Please  Enter Correct Amount..");
//            } else {
//                lb.setCredit(Float.parseFloat(jTextField6.getText()));
//                float bal = lb.getlatestBalance("VNDR"+mStudent.getIdVendorDetails());
//                lb.setBalance(bal - lb.getCredit());
//                lb.setAccountNumber("VNDR"+mStudent.getIdVendorDetails());
//                lb.setDebit(0);
//                if (lb.addToLadger()) {
//                    //JOptionPane.showMessageDialog(null, "Added Successfully");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Error  Ouccured");
//                }
//            }
//        }
//        Session ses = HibernateUtil.getSessionFactory().openSession();
//        Vendordetails vendor = Utility.getVendorWithID(ses, Integer.parseInt(mStudent.getIdVendorDetails()+""));
//        vendor.setBalance(lb.getBalance());
//        ses.save(vendor);
//        ses.getTransaction().commit();
//        ses.close();
//        Utility.clearRemindersOfCustomerWithZeroBalance();

        updateCustomerLadger();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void tfStudentLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStudentLNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentLNameKeyReleased

    private void tfStudentMNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStudentMNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentMNameKeyReleased

    private void tfSSOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSSOKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b') && (caracter != '.')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfSSOKeyTyped

    private void tfSSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSSOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSSOActionPerformed

    private void tfFathersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFathersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFathersNameActionPerformed

    private void comBoxStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBoxStateMouseEntered

    }//GEN-LAST:event_comBoxStateMouseEntered

    private void comBoxCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBoxCityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityMouseClicked

    private void comBoxCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBoxCityMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityMouseEntered

    private void comBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityActionPerformed

    private void comBoxCityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comBoxCityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCityKeyTyped

    private void tfPinCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPinCodeKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfPinCodeKeyTyped

    private void comBoxAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBoxAddressMouseClicked
    }//GEN-LAST:event_comBoxAddressMouseClicked

    private void comBoxAddressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBoxAddressMouseEntered
        // TODO add your handling code here:\
    }//GEN-LAST:event_comBoxAddressMouseEntered

    private void comBoxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxAddressActionPerformed

    private void comBoxAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comBoxAddressKeyTyped
        //String sch = ((sr.getEditor().getEditorComponent()).getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxAddressKeyTyped

    private void comBoxCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxCountryActionPerformed

    private void tfPinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPinCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPinCodeActionPerformed

    private void comBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxStateActionPerformed

    private void tfStudentMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentMNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentMNameActionPerformed

    private void tfStudentLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentLNameActionPerformed

    private void tfAadharNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAadharNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAadharNumberActionPerformed

    public void as() {
//        int x = jSplitPane1.getDividerLocation();
//        System.out.println("x = " + x);
//        if (x == SplitDividerDefault) {
//            jButton1.setText("<");
//            jSplitPane1.setDividerLocation(SplitDividerEnlarged);
//        } else {
//            jButton1.setText(">");
//            jSplitPane1.setDividerLocation(SplitDividerDefault);
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search1;
    private javax.swing.JLabel Search2;
    private javax.swing.JLabel Search3;
    private javax.swing.JLabel Search4;
    private javax.swing.JLabel Search5;
    private javax.swing.JLabel Search6;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbClass;
    private javax.swing.JCheckBox ckBoxEdit;
    private javax.swing.JComboBox comBoxAddress;
    private javax.swing.JComboBox comBoxCity;
    private javax.swing.JComboBox comBoxCountry;
    private javax.swing.JComboBox comBoxState;
    private javax.swing.JRadioButton creditRB;
    private javax.swing.JRadioButton debitRB;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newButton;
    private javax.swing.JTextArea taRemarks;
    private javax.swing.JTextField tfAadharNumber;
    private javax.swing.JTextField tfCell1;
    private javax.swing.JTextField tfCell2;
    private javax.swing.JTextField tfFathersName;
    private javax.swing.JTextField tfPinCode;
    private javax.swing.JTextField tfSSO;
    private javax.swing.JTextField tfStudentFName;
    private javax.swing.JTextField tfStudentLName;
    private javax.swing.JTextField tfStudentMName;
    // End of variables declaration//GEN-END:variables

    private void serachButtonAction() {
        resetData();
        if (mStudent == null) {
            mStudent = new STUDENT();

        }
        if (mStudent != null) {
//            mStudent.setFIRST_NAME(jTextField2.getText());
//            mStudent.getStdntAddress().setCity(jTextField3.getText());
//            mStudent.setCELL_1(jTextField4.getText());
//            mStudent.setCELL_2(jTextField4.getText());
//            mStudent.setFATHERS_NAME(jTextField5.getText());
//            mStudent.setSSO(jTextField1.getText());
//        if (jTextField1.getText().length() != 0) {
//            cb.setIdCustomerDetails(Integer.parseInt(jTextField1.getText()));
//        } else {
//            cb.setIdCustomerDetails(0);
//        }
            searchData = Utility.searchStudent();
            Vector cols = new Vector();
            cols.addElement("SSO");
            cols.addElement("Name");
            cols.addElement("Last N");
            cols.addElement("Father N");
            cols.addElement("Village");
            cols.addElement("Cell");
            cols.addElement("Tell");
            cols.addElement("Sr No.");

            dtm.setDataVector(searchData, cols);
        }
    }

    private void updateStudentsDTLS() {
        if (mStudent != null) {
            tfStudentFName.setText(mStudent.getFIRST_NAME());
            tfStudentMName.setText(mStudent.getMIDDLE_NAME());
            tfStudentLName.setText(mStudent.getLAST_NAME());
            tfFathersName.setText(mStudent.getFATHERS_NAME());
            tfCell1.setText(mStudent.getCELL_1());
            tfCell2.setText(mStudent.getCELL_2());
            tfSSO.setText(mStudent.getSSO());
            tfAadharNumber.setText(mStudent.getAADHAR());
            if (mStudent.getDOB() != null) {
                dob.setDate(mStudent.getDOB());
            } else {
                dob.setDate(null);
            }
            if (mStudent.getIdClass() != null) {
                cbClass.setSelectedItem(mStudent.getIdClass().getIdClass() + "~" + mStudent.getIdClass().getNameOfClass());
            } else {
                cbClass.setSelectedIndex(0);
            }
            if (mStudent.getStdntAddress() != null) {
                comBoxAddress.setEditable(true);
                comBoxCity.setEditable(true);
                comBoxCountry.setEditable(true);
                comBoxState.setEditable(true);
                ((JTextField) comBoxAddress.getEditor().getEditorComponent()).setText(mStudent.getStdntAddress().getAddress());
                if (mStudent.getStdntAddress().getIdBusFee() != null) {
                    ((JTextField) comBoxCity.getEditor().getEditorComponent()).
                            setText(mStudent.getStdntAddress().getIdBusFee().getVILLAGENAME());
                } else {
                    ((JTextField) comBoxCity.getEditor().getEditorComponent()).
                            setText("");
                }
                ((JTextField) comBoxState.getEditor().getEditorComponent()).setText(mStudent.getStdntAddress().getState());
                ((JTextField) comBoxCountry.getEditor().getEditorComponent()).setText(mStudent.getStdntAddress().getCountry());
                tfPinCode.setText(mStudent.getStdntAddress().getPinCode() + "");
                taRemarks.setText(mStudent.getStdntAddress().getRemark());
            }
        }
    }

    private void addModifyVendorDetails() {
        String str = tfStudentFName.getText();
        if (str.length() != 0) {
            Session ses = HibernateUtil.getSessionFactory().openSession();
            ses.beginTransaction();
            try {
                if (mStudent == null) {
                    mStudent = new STUDENT();
                    mStudent.setStdntAddress(new ADDRESS());
                } else if (mStudent.getIdStudent() != null) {
                    mStudent = Utility.getStudentWithID(mStudent.getIdStudent(), ses);
                    ADDRESS lAd = Utility.getAddressWithId(mStudent.getStdntAddress().getIdAddress(), ses);
                    if (lAd != null) {
                        mStudent.setStdntAddress(lAd);
                    } else {
                        mStudent.setStdntAddress(new ADDRESS());
                    }
                }
                mStudent.setFIRST_NAME(tfStudentFName.getText());
                mStudent.setMIDDLE_NAME(tfStudentMName.getText());
                mStudent.setLAST_NAME(tfStudentLName.getText());
                mStudent.setSSO(tfSSO.getText());
                mStudent.setCELL_1(tfCell1.getText());
                mStudent.setCELL_2(tfCell2.getText());
                mStudent.setFATHERS_NAME(tfFathersName.getText());
                mStudent.setAADHAR(tfAadharNumber.getText());
                str = ((JTextField) comBoxAddress.getEditor().getEditorComponent()).getText();
                mStudent.getStdntAddress().setAddress(str);
                str = ((JTextField) comBoxCity.getEditor().getEditorComponent()).getText();
                BUSFEE lbuBusfee = null;
                if (str.length() > 0) {
                    lbuBusfee = Utility.getBusWithCity(str, ses);
                    if (lbuBusfee == null) {
                        lbuBusfee = new BUSFEE();
                        lbuBusfee.setBUSNAME("");
                        lbuBusfee.setBUSNUMBER("");
                        lbuBusfee.setDRIVERCELL("");
                        lbuBusfee.setDRIVERNAME("");
                        lbuBusfee.setFARE((float) 0.0);
                        lbuBusfee.setVILLAGENAME(str);
                        ses.save(lbuBusfee);
                    }
                }
                mStudent.getStdntAddress().setIdBusFee(lbuBusfee);
                str = ((JTextField) comBoxCountry.getEditor().getEditorComponent()).getText();
                mStudent.getStdntAddress().setCountry(str);
                str = ((JTextField) comBoxState.getEditor().getEditorComponent()).getText();
                mStudent.getStdntAddress().setState(str);
                if (tfPinCode.getText().length() != 0) {
                    mStudent.getStdntAddress().setPinCode(Integer.parseInt(tfPinCode.getText()));
                }
                mStudent.setDOB(dob.getDate());
                mStudent.getStdntAddress().setRemark(taRemarks.getText());
                String lstrT = (String) cbClass.getSelectedItem();
                if (!lstrT.equalsIgnoreCase("Not Enrolled")) {
                    int liIdClass = Integer.parseInt(lstrT.split("~")[0]);
                    CLASS lCls = Utility.getClassWithID(liIdClass, ses);
                    mStudent.setIdClass(lCls);
                }
                int lRet = -1;
                if (mStudent.getIdStudent() == null) {
                    lRet = Utility.saveStudentToDB(mStudent, ses);
                } else {
                    lRet = Utility.updateStudentToDB(mStudent, ses);
                }
                if (lRet == 1) {
                    JOptionPane.showMessageDialog(this, "Details stored succesfully..");
                    if (lRet == 1) {
                        ses.getTransaction().commit();
                    } else {
                        ses.getTransaction().rollback();
                    }
                    setAllItemsEditableFalse();
                    ckBoxEdit.setSelected(false);
                    newButton.setEnabled(true);
                    serachButtonAction();
                } else {
                    JOptionPane.showMessageDialog(this, "Unexpected Error ouccured while saving student details ERROR CODE:" + lRet);
                }
            } catch (Exception e) {
                e.printStackTrace();
                ses.getTransaction().rollback();
            } finally {
                ses.close();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter Name");
        }
    }

    private void setAllItemsEditableFalse() {
        jComboBox11.setEditable(false);
        jComboBox12.setEditable(false);
        jComboBox13.setEditable(false);
        jComboBox14.setEditable(false);
        comBoxCity.setEditable(false);
        jComboBox9.setEditable(false);
        tfFathersName.setEditable(false);
        tfStudentFName.setEditable(false);
        tfAadharNumber.setEditable(true);

        tfCell1.setEditable(false);
        tfCell2.setEditable(false);
        tfSSO.setEditable(false);
        jTextField21.setEditable(false);
        jTextField22.setEditable(false);
        jTextField23.setEditable(false);
        bSave.setEnabled(false);
        tfStudentFName.setEditable(false);
        tfStudentMName.setEditable(false);
        tfStudentLName.setEditable(false);
        tfSSO.setEditable(false);
        tfCell1.setEditable(false);
        tfCell2.setEditable(false);
        tfFathersName.setEditable(false);
        tfPinCode.setEditable(false);
        comBoxAddress.setEditable(false);
        comBoxCity.setEditable(false);
        comBoxCountry.setEditable(false);
        comBoxState.setEditable(false);
        taRemarks.setEditable(false);
        dob.setEnabled(false);

    }

    private void setAllItemsEditableTrue() {
        jComboBox11.setEditable(true);
        jComboBox12.setEditable(true);
        jComboBox13.setEditable(true);
        jComboBox14.setEditable(true);
        jComboBox9.setEditable(true);
        tfFathersName.setEditable(true);
        tfStudentFName.setEditable(true);
        tfAadharNumber.setEditable(true);
        tfCell1.setEditable(true);
        tfCell2.setEditable(true);
        tfSSO.setEditable(true);
        jTextField21.setEditable(true);
        jTextField22.setEditable(true);
        jTextField23.setEditable(true);
        bSave.setEnabled(true);
        tfStudentFName.setEditable(true);
        tfStudentMName.setEditable(true);
        tfStudentLName.setEditable(true);
        tfSSO.setEditable(true);
        tfCell1.setEditable(true);
        tfCell2.setEditable(true);
        tfFathersName.setEditable(true);
        tfPinCode.setEditable(true);
        comBoxAddress.setEditable(true);
        comBoxCity.setEditable(true);
        comBoxCountry.setEditable(true);
        comBoxState.setEditable(true);
        taRemarks.setEditable(true);
        dob.setEnabled(true);

    }

    private boolean checkOfSave() {
        if (ckBoxEdit.isSelected()) {
            int choice = JOptionPane.showConfirmDialog(null, "Do You Want To Save Details?");
            if (choice == 0) {
                addModifyVendorDetails();
                return false;
            }
        }
        return true;
    }

//    private void fillNameList() {
//        nameList = cb.getVectorOfCities();
//        jComboBox6.setModel(new DefaultComboBoxModel(nameList));
////        jComboBox6.setEditable(true);
//        ComboBoxSearchEnable s17NonStrict = new ComboBoxSearchEnable(jComboBox6);
////        ((JTextField) jComboBox5.getEditor().getEditorComponent()).setText(ab.getType());
//    }
//    
    private void resetData() {
        mStudent = null;
        updateStudentsDTLS();
    }

    private void serachActive() {
//        resetData();

        mStudent.setFIRST_NAME(tfStudentFName.getText());
//        cb.setVillage(jTextField3.getText());
//        cb.setPhone_1(jTextField4.getText());
//        cb.setPhone_2(jTextField4.getText());
//        cb.setFatherName(jTextField5.getText());
//        if (jTextField1.getText().length() != 0) {
//            cb.setIdCustomerDetails(Integer.parseInt(jTextField1.getText()));
//        } else {
//            cb.setIdCustomerDetails(0);
//        }
//        searchData = mStudent.customerSearch();
        Vector cols = new Vector();
        cols.addElement("A/C No.");
        cols.addElement("Name");
        cols.addElement("Father Name");
        cols.addElement("Village");
        cols.addElement("Phone_1");
        cols.addElement("Vhone_2");

//        dtm.setDataVector(searchData, cols);
    }

    private void printToPDF() {

        //    int roc = dtm.size(), noc = ((Vector) dtm.elementAt(0)).size();
//        PdfPTable table = new PdfPTable(8);
//        PdfPCell cell = new PdfPCell(new Phrase("ACCOUNT NUMBER :" + mStudent.getAccountNumber()));
//        cell.setColspan(8);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Name :" + mStudent.getName()));
//        cell.setColspan(3);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Ocup./Surname :" + mStudent.getFatherName()));
//        cell.setColspan(3);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Villege  :" + mStudent.getVillage()));
//        cell.setColspan(2);
//        table.addCell(cell);
//        cell = new PdfPCell(new Phrase("Phone  :" + mStudent.getPhone_1() + "," + mStudent.getPhone_2()));
//        cell.setColspan(8);
//        table.addCell(cell);
//
//        Vector cols = new Vector();
//        cols.addElement("Sr No.");
//        cols.addElement("Date");
//        cols.addElement("Particulars");
//        cols.addElement("Folio");
//        cols.addElement("Debit");
//        cols.addElement("Credit");
//        cols.addElement("Dr. or Cr.");
//        cols.addElement("Balance");
//
//        for (int i = 0; i < cols.size(); i++) {
//            String stmp = "" + cols.elementAt(i);
//            cell = new PdfPCell(new Phrase(stmp));
//            cell.setColspan(1);
//            table.addCell(cell);
//        }
//        Vector dtm = lb.getDetailsof(mStudent.getAccountNumber());
//
//        for (int i = 0; i < dtm.size(); i++) {
//
//            Vector tv = (Vector) dtm.elementAt(i);
//            for (int j = 0; j < tv.size(); j++) {
//                String stmp = "" + tv.elementAt(j);
//                cell = new PdfPCell(new Phrase(stmp));
//                cell.setColspan(1);
//                table.addCell(cell);
//            }
//        }
//        if (dtm.size() < 60) {
//            for (int i = 0; i < (30 - dtm.size()) * 8; i++) {
//                cell = new PdfPCell(new Phrase(" "));
//                cell.setColspan(1);
//                table.addCell(cell);
//            }
//        }
//        Document document = new Document();
//        try {
//            String fname = mStudent.getAccountNumber();
//            if (mStudent.getAccountNumber().length() == 0) {
//                fname = mStudent.getSrNo() + "";
//            }
//            PdfWriter.getInstance(document, new FileOutputStream("D:\\MAKIMS\\" + fname + ".PDF"));
//            document.open();
//            document.add(table);
//            document.close();
//            JOptionPane.showMessageDialog(null, "Document Printed Sucessfully and Stored.");
//        } catch (Exception ex) {
//            Logger.getLogger(StudentList.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void updateCustomerLadger() {
//        Vector rows = lb.getDetailsof("VNDR"+mStudent.getIdVendorDetails());
//        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//        Vector cols = new Vector();
//        cols.addElement("Sr No.");
//        cols.addElement("Date");
//        cols.addElement("Particulars");
//        cols.addElement("Folio");
//        cols.addElement("Debit");
//        cols.addElement("Credit");
//        cols.addElement("Dr. or Cr.");
//        cols.addElement("Balance");
//        dtm.setDataVector(rows, cols);
//        scrollJTable1();
    }

    private void scrollJTable1() {
        jTable1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e); //To change body of generated methods, choose Tools | Templates.
                jTable1.changeSelection(jTable1.getRowCount(), 0, false, false);
            }
        });
    }
}
