package Hibernate.Entity;
// Generated Oct 8, 2014 6:52:37 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CLASS generated by hbm2java
 */
public class CLASS implements java.io.Serializable {

    private Integer idClass;
    private String nameOfClass;
    private Date fromYear;
    private Date toYear;

    public Date getFromYear() {
        return fromYear;
    }

    public void setFromYear(Date fromYear) {
        this.fromYear = fromYear;
    }

    public Date getToYear() {
        return toYear;
    }

    public void setToYear(Date toYear) {
        this.toYear = toYear;
    }

    private float lateFeePercent;
    private int penaltyCycle;
    private Date lastUpdate;
    private FEEDETAILS feeDetails;
    private int dueDay;

    public int getDueDay() {
        return dueDay;
    }

    public void setDueDay(int dueDay) {
        this.dueDay = dueDay;
    }

    private Set studentsSet = new HashSet(0);

    public FEEDETAILS getFeeDetails() {
        return feeDetails;
    }

    public void setFeeDetails(FEEDETAILS feeDetails) {
        this.feeDetails = feeDetails;
    }

    public String getNameOfClass() {
        return nameOfClass;
    }

    public void setNameOfClass(String nameOfClass) {
        this.nameOfClass = nameOfClass;
    }

    public float getLateFeePercent() {
        return lateFeePercent;
    }

    public void setLateFeePercent(float lateFeePercent) {
        this.lateFeePercent = lateFeePercent;
    }

    public int getPenaltyCycle() {
        return penaltyCycle;
    }

    public void setPenaltyCycle(int penaltyCycle) {
        this.penaltyCycle = penaltyCycle;
    }

    public Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

//     private Set vendors = new HashSet(0);
    public CLASS() {
    }

    public Integer getIdClass() {
        return idClass;
    }

    public void setIdClass(Integer idClass) {
        this.idClass = idClass;
    }

}
