package Hibernate.Entity;
// Generated Oct 8, 2014 6:52:37 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FEEDETAILS generated by hbm2java
 */
public class FEEDETAILS implements java.io.Serializable {

    private Integer idFeeDetails;
    private String remarK;
    private float totalFee;
    private float tutionFee;
    private float libraryFee;
    private float stationaryFee;
    private float dressFee;
    private float miscFee;

    public Integer getIdFeeDetails() {
        return idFeeDetails;
    }

    public void setIdFeeDetails(Integer idFeeDetails) {
        this.idFeeDetails = idFeeDetails;
    }

    public String getRemarK() {
        return remarK;
    }

    public void setRemarK(String remarK) {
        this.remarK = remarK;
    }

    public float getTotalFee() {
        return totalFee;
    }

    public void setTotalFee(float totalFee) {
        this.totalFee = totalFee;
    }

    public float getTutionFee() {
        return tutionFee;
    }

    public void setTutionFee(float tutionFee) {
        this.tutionFee = tutionFee;
    }

    public float getLibraryFee() {
        return libraryFee;
    }

    public void setLibraryFee(float libraryFee) {
        this.libraryFee = libraryFee;
    }

    public float getStationaryFee() {
        return stationaryFee;
    }

    public void setStationaryFee(float stationaryFee) {
        this.stationaryFee = stationaryFee;
    }

    public float getDressFee() {
        return dressFee;
    }

    public void setDressFee(float dressFee) {
        this.dressFee = dressFee;
    }

    public float getMiscFee() {
        return miscFee;
    }

    public void setMiscFee(float miscFee) {
        this.miscFee = miscFee;
    }
    
    
    
}
